### PR TITLE
quarto update

### PR DESCRIPTION
**Pull request by rogin123**
update website to quarto

### CODE REVIEW

**Review by awunderground — CHANGES_REQUESTED** [review]
This is great! A few comments/questions:

1. The nav bars disappears when I scroll down and reappears when I scroll up. Is this difficult to change.
2. The spacing on the last example of "Getting Data" changed. 
3. What is the .quarto/ directory?
4. Can we delete the old_rmd/ directory?
5. MOST IMPORTANT: how does the current directory structure work with GitHub pages? I just added you to tidysynthesis-documentation/ so you can see how I set up a page elsewhere. I think we also need .nojekyll

**Comment by cdavisurban** [comment]
Just uploaded a few changes in preparation for adding content: 

- Added a requirements.R file to install the dependencies for the site easier. Not sure if you have an existing workflow to do this. 
- Fixed a problem with optimization.qmd: there were quotation marks in some of the website links, which for me was causing the website not to render. 
- Exchanged Kyle for Amy on many of the pages. 

@awunderground I noticed that the "Vectors" and "Data Frames" subsections of the "Intro-to-R" .qmd seem unfinished or with  accidentally deleted language, or just moved around (in the case of "Data Frames"). Also saw you had a note for yourself in there. For what it's worth, I'm seeing these live on the R Users Group website. Would you like us to update, or did you have something in mind?

**Comment by awunderground** [comment]
@cdavisurban I just spoke with Amy about some changes that need to happen for the site to render. 

Yeah, that's just an oversight and we can fix it.

**Comment by cdavisurban** [comment]
> @cdavisurban I just spoke with Amy about some changes that need to happen for the site to render.
> 
> Yeah, that's just an oversight and we can fix it.

@awunderground sounds good. Also flagging there's probably some content we can add to the "spatial join" portion of the mapping guide.

**Review by awunderground — APPROVED** [review]

**Pull request merged**
